sudo: false
language: php
branches:
  only:
  - master
notifications:
  email: false

.template_phpunit: &phpunit
  services:
  - docker
  before_install:
  - stty cols 120
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - ./tests/setup.sh
  install: composer install --no-interaction --no-progress --ansi
  script: ./tests/run.sh
  cache:
    directories:
    - $HOME/.composer/cache/files
.template_phpunit_low: &phpunit_low
  <<: *phpunit
  install: composer update --no-interaction --no-progress --ansi --prefer-lowest --prefer-stable
.template_phpunit_high: &phpunit_high
  <<: *phpunit
  install: composer update --no-interaction --no-progress --ansi

jobs:
  include:
  - stage: standards
    php: 7.2
    cache:
      directories:
      - $HOME/.php-cs-fixer
    install:
    - composer require "friendsofphp/php-cs-fixer:^2.11"
    script:
    - vendor/bin/php-cs-fixer fix --config=.php_cs --verbose --diff --dry-run
  - stage: test
    <<: *phpunit
    php: 5.5
  - <<: *phpunit
    php: 5.6
  - <<: *phpunit_low
    php: 7.0
  - <<: *phpunit
    php: 7.1
  - <<: *phpunit_high
    php: 7.2
